### ISSUE TITLE
Error create endpoint

### ISSUE THREAD

**Issue by jeffersongoncalves** [ioneyed/generator-expressjs-api#4]
yo expressjs-api:endpoint category

events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'sequelizeModels' of undefined
    at Generator.prompting (D:/npm-packages/node_modules/generator-expressjs-api/endpoint/generator.js:91:30)
    at D:\npm-packages\node_modules\generator-expressjs-api\node_modules\yeoman-generator\lib\base.js:429:16
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback](timers.js:533:5)

**Comment by ioneyed** [comment]
What does your package.json look like and what version of nodejs. I will try to recreate it.

**Comment by jeffersongoncalves** [comment]
Hello, I lacked a **.yo-rc.json** file in the root of the project and so it is in error in creating the endpoint.
